apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    matchLabels:
      app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
